title: Atishay Jain # your name (or website title) here
logo: "/images/logo.png?raw=false" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Student Developer'20 @Crio.Do | Competitive Programmer 
  <br><br>
  Android Developer, Student, and love to do competitive programming. I love to learn new things and challenges. 
  <br><br>
  <a href="https://www.linkedin.com/in/atishay-jain-749318171/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-173588431-1 # your Google Analytics tracking ID here
